### ISSUE TITLE
HW4 - How should we handle empty conditions and constant ones?

### ISSUE THREAD

**Issue by leporia** [swtv-kaist/cs458-spring24#10]
For example
```
for (;;) {
    // code
}
```
Should we count it as no branch as it is not branching?

Also things like
```
while (1) {}
```
I imagine in this case we don't need to do constant expression evaluation/propagation so we just count it as 2 branches?

Additionally should we also consider break statements? As they are adding edges in the CFG

**Comment by swtv-kaist** [comment]
> For example
> for (;;) {
>    // code
> }
> Should we count it as no branch as it is not branching?

We should consider that the code has branches, since it has branches.  ```gcov``` does not know if a given branch is reachable or not (as it is an undecidable problem). 
 
> Additionally should we also consider break statements? As they are adding edges in the CFG

No, we do not count ```break```, ```goto``` as a branch.  What we call as a branch is a (conditional) branch.
Measuring coverage of unconditional branches does not make sense becauase unconditional branches will be always executed.

**Comment by leporia** [comment]
Thanks it makes sense.
What about constant expressions inside enums or other statements that only take integer constants. For example
```
enum {
  VALUE_ONE = (1 > 0) ? 1 : 2,
  VALUE_TWO = (2 > 1) ? 2 : 1,
}
```

As we know that it only contain constants it is not a branch? Is that correct?

**Comment by moonzoo** [comment]
Good question!  ```enum``` allows only constant expressions that can be evaluated at compile time.  Thus, no branches in ```enum``` are generated in a target executable.
You can double check it by making a toy example code and apply ```gcov```.

**Comment by leporia** [comment]
All clear, thanks!
